# Generated by Django 3.2.25 on 2024-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20240711_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=1, upload_to='static/image'),
            preserve_default=False,
        ),
    ]
